### ISSUE TITLE
How to generate modelnet40_60x as you say?

### ISSUE THREAD

**Issue by Jihao-Li** [barrykui/3ddensenet.torch#1]
Hello! Thank you for your contribution. I am confusing the ModelNet40 dataset. 
The format of ModelNet40 downloaded from `http://3dshapenets.cs.princeton.edu/` is *.off while the format is *.h5 when the dataset is in modelnet40_ply_hdf5_2048. How to transform *.off files to *.h5 files? Could you please give me some guidances?
Thank you very much!

**Comment by kuixu** [comment]
Have you find the code in [Princeton Vision Toolkit (PVT)](http://3dvision.princeton.edu/code.html)?

As mentioned in the project webpage:
> The CAD models are in Object File Format (OFF). We also provide Matlab functions to read and visualize OFF files in our Princeton Vision Toolkit (PVT).

**Comment by Jihao-Li** [comment]
Thank you very much! 
I have learned the visualization method. And do you know how to transform [ModelNet40](http://modelnet.cs.princeton.edu/ModelNet40.zip) to [modelnet40_ply_hdf5_2048](https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip)? [Princeton Vision Toolkit (PVT)](http://3dvision.princeton.edu/code.html) does not provide this function.

**Comment by kuixu** [comment]
I do not use that file, but I notice that the file is provided by the official ModelNet Dataset website, have you ask for the author's ([Suran Song](https://shurans.github.io/)) help?

**Comment by Jihao-Li** [comment]
OK. Thank you very much! I will have a try.
